package com.example.apexauto.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;
import java.util.List;


// This is the Vehicle entity class that represents the vehicles in the application. It contains fields for vehicle information and a relationship to the User entity.
@Table(name = "vehicles")
@Entity
@AllArgsConstructor
@NoArgsConstructor
public class Vehicle {

    // The unique identifier for each vehicle, automatically generated by the database.
    @Getter
    @Setter
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(nullable = false)
    private int vehicleId;

    // This is the brand or manufacturer of the vehicle, such as Toyota, Ford, etc. It is a required field.
    @Getter
    @Setter
    @Column(nullable = false)
    private String brand;

    // The make of the vehicle, which is a required field.
    @Getter
    @Setter
    @Column(nullable = false)
    private String make;

    // The model of the vehicle, which is a required field.
    @Setter
    @Getter
    @Column(nullable = false)
    private String model;

    // The year of the vehicle, which is a required field.
    @Getter
    @Setter
    @Column(nullable = false)
    private int year;

    // This is the color of the vehicle, which is a required field.
    @Getter
    @Setter
    @Column(nullable = false)
    private String color;

    // The category of the vehicle, e.g. Sedan, Sports, SUV, Luxury. Required field.
    @Getter
    @Setter
    @Column(nullable = false)
    private String category;

    // The number of doors the vehicle has, which is a required field.
    @Getter
    @Setter
    @Column(nullable = false)
    private int doors;

    // The number of seats in the vehicle, which is a required field.
    @Getter
    @Setter
    @Column(nullable = false)
    private int seats;

    // The emission score of the vehicle, which is a required field.
    @Getter
    @Setter
    @Column(nullable = false)
    private double emissionScore;

    // The fuel usage of the vehicle, which is a required field.
    @Getter
    @Setter
    @Column(nullable = false)
    private double fuelUsage;

    // The mileage of the vehicle, which is a required field.
    @Getter
    @Setter
    @Column(nullable = false)
    private double mileage;

    // A boolean field indicating whether the vehicle is currently on sale, which is a required field.
    @Getter
    @Setter
    @Column(nullable = false)
    private boolean isOnSale;

    // A boolean field indicating whether the vehicle is currently in stock, which is a required field.
    @Getter
    @Setter
    @Column(nullable = false)
    private boolean isInStock;

    // The number of units currently available in inventory.
    @Getter
    @Setter
    @Column(nullable = false)
    private int amountInStock;

    // The price of the vehicle, which is a required field.
    @Getter
    @Setter
    @Column(nullable = false)
    private BigDecimal price;

    // Optional image for the vehicle (URL or data URI). Null/blank means the frontend falls back to a default image.
    @Getter
    @Setter
    @Column(columnDefinition = "LONGTEXT")
    private String imageUrl;

    // The favourites associated with this vehicle. When a vehicle is deleted, all related favourites are also deleted to satisfy the foreign key constraint.
    @Getter
    @Setter
    @OneToMany(mappedBy = "vehicle", cascade = CascadeType.REMOVE)
    private List<Favourites> favourites;
}
